/**
 * Strategy types
 */

import type { ContractDirection } from './trade.js';

/**
 * Trading signal generated by a strategy
 */
export interface Signal {
  /** Asset symbol */
  symbol: string;
  /** Asset (alias for symbol, for compatibility) */
  asset?: string;
  /** Direction */
  direction: ContractDirection;
  /** Confidence level (0-100) */
  confidence: number;
  /** Timestamp */
  timestamp: number;
  /** Strategy that generated this signal */
  strategyName: string;
  /** Reason/explanation */
  reason?: string;
  /** Additional metadata */
  metadata?: Record<string, unknown>;
}

/**
 * Strategy configuration
 */
export interface StrategyConfig {
  /** Strategy name (unique identifier) */
  name: string;
  /** Whether strategy is enabled */
  enabled: boolean;
  /** Assets to trade */
  assets: string[];
  /** Max concurrent trades */
  maxConcurrentTrades: number;
  /** Trade amount (fixed or percentage) */
  amount: number;
  /** Amount type */
  amountType: 'fixed' | 'percentage';
  /** Cooldown between trades (seconds) */
  cooldownSeconds: number;
  /** Minimum confidence to execute */
  minConfidence: number;
  /** Strategy-specific parameters */
  parameters: Record<string, unknown>;
}

/**
 * Strategy metrics/performance
 */
export interface StrategyMetrics {
  /** Strategy name */
  name: string;
  /** Total trades executed */
  totalTrades: number;
  /** Winning trades */
  winningTrades: number;
  /** Losing trades */
  losingTrades: number;
  /** Win rate (0-1) */
  winRate: number;
  /** Total profit/loss */
  totalPnL: number;
  /** Average profit per trade */
  averageProfit: number;
  /** Max consecutive wins */
  maxWinStreak: number;
  /** Max consecutive losses */
  maxLossStreak: number;
  /** Current streak */
  currentStreak: number;
  /** Sharpe ratio */
  sharpeRatio?: number;
  /** Max drawdown */
  maxDrawdown: number;
  /** Active trades count */
  activeTrades: number;
}

/**
 * Signal proximity information - how close a strategy is to generating a signal
 */
export interface SignalProximity {
  /** Asset symbol */
  asset: string;
  /** Direction the signal would be for */
  direction: 'call' | 'put' | 'neutral';
  /** Overall proximity percentage (0-100) */
  overallProximity: number;
  /** Criteria that need to be met */
  criteria: Array<{
    name: string;
    current: number;
    target: number;
    unit: string;
    passed: boolean;
    distance: number;
  }>;
  /** Whether the signal is ready to be generated */
  readyToSignal: boolean;
  /** Missing criteria names */
  missingCriteria: string[];
}
