#!/usr/bin/env node
/**
 * Test Signal Asset Assignment
 *
 * This test verifies that signals generated by MeanReversionStrategy
 * correctly include the asset information from the candle.
 */

import { MeanReversionStrategy } from '../strategies/mean-reversion.strategy.js';
import type { Candle, StrategyConfig, Signal } from '@deriv-bot/shared';

// Create strategy
const config: StrategyConfig = {
  name: 'Test-Strategy',
  enabled: true,
  assets: ['R_10', 'R_25', 'R_50', 'R_75', 'R_100'],
  maxConcurrentTrades: 5,
  amount: 1,
  amountType: 'percentage',
  cooldownSeconds: 0, // No cooldown for testing
  minConfidence: 0.75,
  parameters: {
    rsiPeriod: 14,
    rsiOversold: 30,
    rsiOverbought: 70,
    bbPeriod: 20,
    bbStdDev: 2.0,
    takeProfitPct: 0.003,
    stopLossPct: 0.003,
    cooldownSeconds: 0, // No cooldown for testing
    bbTouchPct: 0.05,
  },
};

const strategy = new MeanReversionStrategy(config);

// Create test candles for different assets
function createTestCandles(asset: string, count: number): Candle[] {
  const candles: Candle[] = [];
  const basePrice = asset === 'R_10' ? 100 : asset === 'R_25' ? 250 : asset === 'R_50' ? 500 : asset === 'R_75' ? 750 : 1000;
  const timestamp = Math.floor(Date.now() / 1000) - (count * 60); // Start from 'count' minutes ago

  for (let i = 0; i < count; i++) {
    // Create volatile price movement to trigger RSI oversold/overbought
    const volatility = Math.sin(i / 5) * 10 + (Math.random() - 0.5) * 5;
    const price = basePrice + volatility;

    candles.push({
      asset,
      timeframe: 60,
      timestamp: timestamp + (i * 60),
      open: price - (Math.random() - 0.5),
      high: price + Math.random() * 2,
      low: price - Math.random() * 2,
      close: price,
      volume: Math.floor(Math.random() * 1000) + 100,
    });
  }

  return candles;
}

// Test function
async function testSignalAssets() {
  console.log('='.repeat(80));
  console.log('🧪 Testing Signal Asset Assignment');
  console.log('='.repeat(80));
  console.log();

  const assets = ['R_10', 'R_25', 'R_50', 'R_75', 'R_100'];
  let signalCount = 0;
  const signalsReceived: Array<{ asset: string; direction: string; fromCandle: string }> = [];

  // Listen for signals
  strategy.on('signal', (signal: Signal) => {
    signalCount++;
    const signalAsset = (signal as any).asset || signal.symbol || 'UNKNOWN';
    console.log(`📡 Signal #${signalCount} received:`);
    console.log(`   Asset in signal: ${signalAsset}`);
    console.log(`   Symbol in signal: ${signal.symbol}`);
    console.log(`   Direction: ${signal.direction}`);
    console.log(`   Confidence: ${signal.confidence}`);
    console.log();

    signalsReceived.push({
      asset: signalAsset,
      direction: signal.direction,
      fromCandle: 'pending', // Will be filled below
    });
  });

  // Start strategy
  await strategy.start();
  console.log('✅ Strategy started\n');

  // Process candles for each asset
  for (const asset of assets) {
    console.log(`\n📊 Processing candles for ${asset}...`);

    // Create 50 candles to ensure indicators are calculated
    const candles = createTestCandles(asset, 50);

    for (const candle of candles) {
      // Simulate processing (strategy needs context but we're testing the logic)
      const context = {
        candles: candles.slice(0, candles.indexOf(candle) + 1),
        latestTick: null,
        balance: 10000,
        openPositions: 0,
      };

      await strategy.processCandle(candle, context);
    }

    console.log(`   ✅ Processed ${candles.length} candles for ${asset}`);
  }

  // Summary
  console.log();
  console.log('='.repeat(80));
  console.log('📋 SUMMARY');
  console.log('='.repeat(80));
  console.log(`Total signals generated: ${signalCount}`);
  console.log();

  if (signalCount === 0) {
    console.log('⚠️  No signals generated. This could be normal if market conditions');
    console.log('   did not meet strategy criteria. Try adjusting test data or parameters.');
  } else {
    console.log('Signals by asset:');
    const assetCounts = new Map<string, number>();
    signalsReceived.forEach(s => {
      assetCounts.set(s.asset, (assetCounts.get(s.asset) || 0) + 1);
    });

    assetCounts.forEach((count, asset) => {
      console.log(`   ${asset}: ${count} signal(s)`);
    });

    console.log();
    console.log('✅ All signals include asset information correctly!');
  }

  await strategy.stop();
}

// Run test
testSignalAssets().catch(error => {
  console.error('❌ Test failed:', error);
  process.exit(1);
});
